version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tenet-runtime

hooks:
  ApplicationStop:
    - location: codedeploy/stop.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: codedeploy/start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: codedeploy/validate.sh
      timeout: 300
      runas: ec2-user
