name: CI for tenet runtime

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (multi-line supported)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: amd64
      GOFLAGS: -mod=vendor

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      
      - name: Run Go Mod Tidy
        run: go mod tidy

      - name: Run Go Mod Vendor deps
        run: go mod vendor

      - name: Build Go Plugin
        run: |
          go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false

      - name: Upload backend.so to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./backend.so
          asset_name: backend.so
          asset_content_type: application/octet-stream