name: CI for tenet runtime

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (multi-line supported)'
        required: false
        type: string
      branch:
        description: 'Git ref to build (branch or tag)'
        required: false
        default: 'main'
        type: string
    

permissions:
  contents: write
  id-token: write 

env:
  BUNDLE_NAME_PREFIX: tenet-runtime-linux
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_PREFIX: ${{ secrets.S3_PREFIX }}

jobs:
  build-and-release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0  # ensure tags/branches are available

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      
      - name: Run Go Mod Tidy
        run: go mod tidy

      - name: Run Go Mod Vendor deps
        run: go mod vendor

      - name: Build Go Plugin
        run: |
          go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false

      - name: Assemble single bundle (AWS CodeDeploy + artifacts)
        run: |
          set -euo pipefail
          VER="${{ github.event.inputs.version }}"
          mkdir -p dist bundle

          # copy necessaru atrifacts
          cp appspec.yml bundle/
          rsync -a codedeploy/ bundle/codedeploy/
          cp local.yml bundle/
          cp backend.so bundle/
          
          #copy source code
          git fetch --tags
          git archive --format=tar --prefix=source/ "refs/tags/${VER}" | tar -x -C bundle
         
          # bundle everything as a .tar.gz file
          # Create one zip that contains everything
          BUNDLE="${{ env.BUNDLE_NAME_PREFIX }}-${VER}.tar.gz"
          (cd bundle && tar -czf "../dist/${BUNDLE}" .)
          echo "BUNDLE_NAME=${BUNDLE}" >> $GITHUB_ENV
          echo "BUNDLE_PATH=dist/${BUNDLE}" >> $GITHUB_ENV
      
      - name: Generate checksum
        run: |
          set -euo pipefail
          sha256sum "${BUNDLE_PATH}" | tee "${BUNDLE_PATH}.sha256"

      - name: Upload single bundle to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUNDLE_PATH }}
          asset_name: ${{ env.BUNDLE_NAME }}
          asset_content_type: application/zip
      
      - name: Upload checksum to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUNDLE_PATH }}.sha256
          asset_name: ${{ env.BUNDLE_NAME }}.sha256
          asset_content_type: text/plain

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TITAN_STAGING_GAME_SERVICES }}
          aws-region: ${{ secrets.AWS_REGION_TITAN_STAGING_GAME_SERVICES }}
          audience: sts.amazonaws.com
      
      # (Optional) Push the single bundle to S3 via OIDC
      - name: Upload bundle to S3
        run: |
          VER="${{ github.event.inputs.version }}"
          BASE="s3://${S3_BUCKET}/${S3_PREFIX}/${VER}"
          aws s3 cp "${BUNDLE_PATH}"        "${BASE}/${BUNDLE_NAME}"
          aws s3 cp "${BUNDLE_PATH}.sha256" "${BASE}/${BUNDLE_NAME}.sha256"
